# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180805_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_subscriber',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriber',
            field=models.BooleanField(default=True, help_text='Check the box if you want to receive our newsletters.'),
        ),
    ]
