# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180805_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriber',
            field=models.NullBooleanField(default=True, help_text='Check the box if you want to receive our newsletters.'),
        ),
    ]
